---
- name: Health check
  hosts: workshop
  become: true

  tasks:
    - name: Verify Connectivy
      ansible.builtin.ping:

    - name: Gather service status
      ansible.builtin.service_facts:


    - name: Verify sshd is running
      ansible.builtin.assert:
        that:
          - ansible_facts.services['sshd  .service'].state == 'running'
        success_msg: "sshd is running"
        fail_msg: "sshd is NOT running on {{ inventory_hostname }}"
