---
- name: Patch and fix servers
  hosts: workshop
  become: true
  
  vars:
    package_filter: "*"

  tasks:
    - name: Update packages
      ansible.builtin.dnf:
        name: "{{ package_filter }}"
        state: latest
        update_cache: true

    - name: Ensure chronyd is running
      ansible.builtin.service:
        name: chronyd
        state: started


